import { fetchWithRetry } from "./fetchWithRetry";
import { foodQuerySchema } from "@/app/lib/validation";

const NUTRITIONIX_APP_ID = process.env.NEXT_PUBLIC_NUTRITIONIX_APP_ID || "";
const NUTRITIONIX_API_KEY = process.env.NEXT_PUBLIC_NUTRITIONIX_API_KEY || "";

interface NutritionixFood {
    food_name: string;
    serving_qty: number;
    serving_unit: string;
    serving_weight_grams: number;
    nf_calories: number;
    nf_protein: number;
    nf_total_carbohydrate: number;
    nf_total_fat: number;
}

interface NutritionixResponse {
    foods: NutritionixFood[];
}

export async function searchFoodNutrition(query: string): Promise<{
    name: string;
    calories: number;
    protein: number;
    carbs: number;
    fats: number;
    serving: string;
} | null> {
    const result = foodQuerySchema.safeParse(query);
    if (!result.success) {
        throw new Error("Invalid food query: " + result.error.errors[0].message);
    }

    if (!NUTRITIONIX_APP_ID || !NUTRITIONIX_API_KEY) {
        return estimateNutrition(query);
    }

    try {
        const data = await fetchWithRetry<NutritionixResponse>(
            "https://trackapi.nutritionix.com/v2/natural/nutrients",
            {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                    "x-app-id": NUTRITIONIX_APP_ID,
                    "x-app-key": NUTRITIONIX_API_KEY,
                },
                body: JSON.stringify({ query: query.trim() }),
                timeout: 10000,
            },
            2
        );

        if (!data.foods || data.foods.length === 0) {
            return null;
        }

        const food = data.foods[0];
        return {
            name: food.food_name,
            calories: Math.round(food.nf_calories),
            protein: Math.round(food.nf_protein * 10) / 10,
            carbs: Math.round(food.nf_total_carbohydrate * 10) / 10,
            fats: Math.round(food.nf_total_fat * 10) / 10,
            serving: `${food.serving_qty} ${food.serving_unit} (${food.serving_weight_grams}g)`,
        };
    } catch (error) {
        console.warn("Nutritionix API failed, using estimation:", error);
        return estimateNutrition(query);
    }
}

const knownFoods: Record<string, { calories: number; protein: number; carbs: number; fats: number; serving: string }> = {
    rice: { calories: 200, protein: 4, carbs: 44, fats: 0.5, serving: "1 cup cooked" },
    roti: { calories: 90, protein: 3, carbs: 18, fats: 1, serving: "1 medium" },
    chapati: { calories: 90, protein: 3, carbs: 18, fats: 1, serving: "1 medium" },
    dal: { calories: 120, protein: 7, carbs: 18, fats: 2, serving: "1 cup" },
    "moong dal": { calories: 100, protein: 7, carbs: 16, fats: 2, serving: "1 cup" },
    "toor dal": { calories: 110, protein: 7, carbs: 18, fats: 2, serving: "1 cup" },
    "masoor dal": { calories: 105, protein: 7, carbs: 17, fats: 2, serving: "1 cup" },
    "chana dal": { calories: 130, protein: 8, carbs: 20, fats: 3, serving: "1 cup" },
    "urad dal": { calories: 110, protein: 7, carbs: 16, fats: 2, serving: "1 cup" },
    paneer: { calories: 265, protein: 18, carbs: 6, fats: 20, serving: "100g" },
    chicken: { calories: 165, protein: 31, carbs: 0, fats: 3.6, serving: "100g" },
    "chicken curry": { calories: 250, protein: 30, carbs: 6, fats: 12, serving: "1 cup" },
    "chicken tikka": { calories: 200, protein: 28, carbs: 4, fats: 8, serving: "4 pieces" },
    egg: { calories: 70, protein: 6, carbs: 0.6, fats: 5, serving: "1 large" },
    "egg bhurji": { calories: 180, protein: 12, carbs: 4, fats: 12, serving: "2 eggs" },
    poha: { calories: 200, protein: 4, carbs: 40, fats: 6, serving: "1 plate" },
    upma: { calories: 180, protein: 5, carbs: 32, fats: 4, serving: "1 cup" },
    idli: { calories: 60, protein: 2, carbs: 12, fats: 0.5, serving: "1 piece" },
    dosa: { calories: 120, protein: 3, carbs: 20, fats: 3, serving: "1 plain" },
    "masala dosa": { calories: 250, protein: 5, carbs: 38, fats: 8, serving: "1 piece" },
    "sambar rice": { calories: 250, protein: 8, carbs: 45, fats: 4, serving: "1 cup" },
    biryani: { calories: 350, protein: 12, carbs: 50, fats: 10, serving: "1 cup" },
    "chicken biryani": { calories: 350, protein: 16, carbs: 48, fats: 12, serving: "1 cup" },
    "veg biryani": { calories: 280, protein: 8, carbs: 48, fats: 8, serving: "1 cup" },
    "chole bhature": { calories: 500, protein: 12, carbs: 65, fats: 20, serving: "1 plate" },
    "rajma rice": { calories: 300, protein: 12, carbs: 50, fats: 6, serving: "1 cup" },
    paratha: { calories: 180, protein: 4, carbs: 24, fats: 8, serving: "1 medium" },
    "aloo paratha": { calories: 220, protein: 5, carbs: 32, fats: 8, serving: "1 medium" },
    dahi: { calories: 80, protein: 4, carbs: 6, fats: 4, serving: "1 cup" },
    curd: { calories: 80, protein: 4, carbs: 6, fats: 4, serving: "1 cup" },
    buttermilk: { calories: 40, protein: 2, carbs: 4, fats: 1, serving: "1 glass" },
    chaas: { calories: 40, protein: 2, carbs: 4, fats: 1, serving: "1 glass" },
    lassi: { calories: 150, protein: 5, carbs: 20, fats: 5, serving: "1 glass" },
    "green tea": { calories: 0, protein: 0, carbs: 0, fats: 0, serving: "1 cup" },
    "black coffee": { calories: 2, protein: 0, carbs: 0, fats: 0, serving: "1 cup" },
    "milk tea": { calories: 80, protein: 2, carbs: 12, fats: 3, serving: "1 cup" },
    banana: { calories: 90, protein: 1, carbs: 23, fats: 0, serving: "1 medium" },
    apple: { calories: 80, protein: 0.5, carbs: 20, fats: 0, serving: "1 medium" },
    orange: { calories: 60, protein: 1, carbs: 15, fats: 0, serving: "1 medium" },
    grapes: { calories: 60, protein: 0.5, carbs: 16, fats: 0, serving: "1 cup" },
    almonds: { calories: 70, protein: 2.5, carbs: 2.5, fats: 6, serving: "10 pieces" },
    peanuts: { calories: 80, protein: 4, carbs: 2, fats: 7, serving: "handful" },
    "mixed nuts": { calories: 150, protein: 5, carbs: 6, fats: 12, serving: "handful" },
    "chana chaat": { calories: 150, protein: 7, carbs: 22, fats: 3, serving: "1 cup" },
    "roasted chana": { calories: 120, protein: 6, carbs: 20, fats: 2, serving: "1 cup" },
    salad: { calories: 30, protein: 1, carbs: 6, fats: 0, serving: "1 bowl" },
    "fruit salad": { calories: 100, protein: 1, carbs: 24, fats: 0, serving: "1 bowl" },
    "sprouts salad": { calories: 120, protein: 8, carbs: 18, fats: 1, serving: "1 cup" },
    oats: { calories: 150, protein: 5, carbs: 27, fats: 3, serving: "1 cup cooked" },
    pasta: { calories: 220, protein: 8, carbs: 43, fats: 1, serving: "1 cup cooked" },
    noodles: { calories: 200, protein: 5, carbs: 38, fats: 2, serving: "1 cup cooked" },
    pizza: { calories: 300, protein: 12, carbs: 36, fats: 12, serving: "1 slice" },
    burger: { calories: 350, protein: 15, carbs: 35, fats: 16, serving: "1 medium" },
    "french fries": { calories: 250, protein: 3, carbs: 30, fats: 14, serving: "medium serving" },
    samosa: { calories: 150, protein: 3, carbs: 18, fats: 8, serving: "1 piece" },
    pakora: { calories: 120, protein: 2, carbs: 12, fats: 7, serving: "2 pieces" },
    "vada pav": { calories: 300, protein: 6, carbs: 40, fats: 12, serving: "1 piece" },
    "misal pav": { calories: 350, protein: 12, carbs: 45, fats: 12, serving: "1 bowl" },
    "pav bhaji": { calories: 400, protein: 10, carbs: 55, fats: 15, serving: "1 plate" },
    "dosa with chutney": { calories: 180, protein: 4, carbs: 30, fats: 5, serving: "1 piece" },
    uttapam: { calories: 150, protein: 4, carbs: 25, fats: 4, serving: "1 piece" },
    "medu vada": { calories: 120, protein: 3, carbs: 15, fats: 6, serving: "2 pieces" },
    "ragi mudde": { calories: 120, protein: 3, carbs: 24, fats: 1, serving: "1 medium" },
    "jowar roti": { calories: 70, protein: 2, carbs: 15, fats: 0.5, serving: "1 medium" },
    "bajra roti": { calories: 80, protein: 2, carbs: 16, fats: 0.5, serving: "1 medium" },
    "makki roti": { calories: 90, protein: 2, carbs: 18, fats: 1, serving: "1 medium" },
    "sarson ka saag": { calories: 120, protein: 4, carbs: 10, fats: 8, serving: "1 cup" },
    "palak paneer": { calories: 200, protein: 10, carbs: 10, fats: 14, serving: "1 cup" },
    "matar paneer": { calories: 220, protein: 10, carbs: 14, fats: 14, serving: "1 cup" },
    "aloo gobi": { calories: 120, protein: 3, carbs: 18, fats: 5, serving: "1 cup" },
    "bhindi masala": { calories: 100, protein: 2, carbs: 10, fats: 6, serving: "1 cup" },
    "baingan bharta": { calories: 100, protein: 2, carbs: 12, fats: 5, serving: "1 cup" },
    "dal makhani": { calories: 250, protein: 10, carbs: 22, fats: 14, serving: "1 cup" },
    "chana masala": { calories: 220, protein: 10, carbs: 30, fats: 8, serving: "1 cup" },
    "kadhi pakora": { calories: 180, protein: 6, carbs: 18, fats: 9, serving: "1 cup" },
    "tomato soup": { calories: 80, protein: 2, carbs: 14, fats: 2, serving: "1 bowl" },
    "spring roll": { calories: 150, protein: 3, carbs: 20, fats: 7, serving: "1 piece" },
    momos: { calories: 200, protein: 8, carbs: 28, fats: 6, serving: "4 pieces" },
    "chow mein": { calories: 300, protein: 8, carbs: 45, fats: 10, serving: "1 cup" },
    "fried rice": { calories: 280, protein: 6, carbs: 42, fats: 10, serving: "1 cup" },
    "chilli chicken": { calories: 250, protein: 20, carbs: 12, fats: 14, serving: "1 cup" },
    "chilli paneer": { calories: 280, protein: 14, carbs: 14, fats: 18, serving: "1 cup" },
    "gobi manchurian": { calories: 220, protein: 5, carbs: 22, fats: 12, serving: "1 cup" },
    "tandoori chicken": { calories: 200, protein: 28, carbs: 2, fats: 8, serving: "2 pieces" },
    "butter chicken": { calories: 350, protein: 22, carbs: 10, fats: 24, serving: "1 cup" },
    naan: { calories: 200, protein: 6, carbs: 32, fats: 6, serving: "1 piece" },
    "garlic naan": { calories: 220, protein: 6, carbs: 34, fats: 7, serving: "1 piece" },
    "jeera rice": { calories: 180, protein: 3, carbs: 36, fats: 3, serving: "1 cup" },
    pulao: { calories: 220, protein: 4, carbs: 40, fats: 5, serving: "1 cup" },
    "lemon rice": { calories: 200, protein: 4, carbs: 38, fats: 4, serving: "1 cup" },
    "coconut rice": { calories: 230, protein: 4, carbs: 38, fats: 8, serving: "1 cup" },
    "tomato rice": { calories: 210, protein: 4, carbs: 40, fats: 4, serving: "1 cup" },
    "veg pulao": { calories: 200, protein: 5, carbs: 38, fats: 4, serving: "1 cup" },
    "peas pulao": { calories: 210, protein: 5, carbs: 40, fats: 4, serving: "1 cup" },
    "paneer tikka": { calories: 220, protein: 14, carbs: 8, fats: 14, serving: "4 pieces" },
    "hara bhara kebab": { calories: 150, protein: 4, carbs: 16, fats: 8, serving: "2 pieces" },
    "veg cutlet": { calories: 150, protein: 3, carbs: 20, fats: 7, serving: "2 pieces" },
    "aloo tikki": { calories: 120, protein: 2, carbs: 18, fats: 5, serving: "2 pieces" },
    "gol gappa": { calories: 50, protein: 1, carbs: 10, fats: 0, serving: "4 pieces" },
    "dahi bhalla": { calories: 150, protein: 5, carbs: 20, fats: 5, serving: "2 pieces" },
    "papdi chaat": { calories: 200, protein: 4, carbs: 28, fats: 8, serving: "1 plate" },
    "bhel puri": { calories: 180, protein: 4, carbs: 30, fats: 6, serving: "1 cup" },
    "sev puri": { calories: 150, protein: 3, carbs: 22, fats: 6, serving: "4 pieces" },
    "ragda patties": { calories: 220, protein: 6, carbs: 30, fats: 8, serving: "2 pieces" },
    "pani puri": { calories: 100, protein: 2, carbs: 18, fats: 2, serving: "6 pieces" },
    sambar: { calories: 100, protein: 4, carbs: 16, fats: 2, serving: "1 cup" },
    rasam: { calories: 60, protein: 2, carbs: 10, fats: 1, serving: "1 cup" },
    avial: { calories: 120, protein: 3, carbs: 14, fats: 6, serving: "1 cup" },
    kootu: { calories: 100, protein: 4, carbs: 14, fats: 3, serving: "1 cup" },
    poriyal: { calories: 80, protein: 2, carbs: 10, fats: 4, serving: "1 cup" },
    thoran: { calories: 90, protein: 2, carbs: 8, fats: 6, serving: "1 cup" },
    olan: { calories: 80, protein: 2, carbs: 10, fats: 3, serving: "1 cup" },
    erissery: { calories: 110, protein: 3, carbs: 16, fats: 4, serving: "1 cup" },
    "moru curry": { calories: 70, protein: 3, carbs: 6, fats: 3, serving: "1 cup" },
    "fish curry": { calories: 180, protein: 18, carbs: 6, fats: 10, serving: "1 cup" },
    "prawn curry": { calories: 200, protein: 20, carbs: 6, fats: 10, serving: "1 cup" },
    "egg curry": { calories: 180, protein: 12, carbs: 8, fats: 10, serving: "1 cup" },
    "chicken chettinad": { calories: 280, protein: 24, carbs: 8, fats: 18, serving: "1 cup" },
    "mutton rogan josh": { calories: 300, protein: 22, carbs: 6, fats: 20, serving: "1 cup" },
    keema: { calories: 250, protein: 20, carbs: 8, fats: 16, serving: "1 cup" },
    "shami kebab": { calories: 150, protein: 10, carbs: 8, fats: 8, serving: "2 pieces" },
    "seekh kebab": { calories: 180, protein: 12, carbs: 6, fats: 12, serving: "2 pieces" },
    "mutton biryani": { calories: 400, protein: 18, carbs: 50, fats: 14, serving: "1 cup" },
    tehari: { calories: 300, protein: 8, carbs: 50, fats: 8, serving: "1 cup" },
    zarda: { calories: 250, protein: 3, carbs: 50, fats: 5, serving: "1 cup" },
    "sheer khurma": { calories: 250, protein: 6, carbs: 40, fats: 8, serving: "1 cup" },
    phirni: { calories: 200, protein: 5, carbs: 32, fats: 6, serving: "1 cup" },
    kheer: { calories: 220, protein: 5, carbs: 36, fats: 6, serving: "1 cup" },
    payasam: { calories: 220, protein: 5, carbs: 36, fats: 6, serving: "1 cup" },
    basundi: { calories: 250, protein: 7, carbs: 30, fats: 10, serving: "1 cup" },
    rabri: { calories: 280, protein: 8, carbs: 32, fats: 12, serving: "1 cup" },
    "gulab jamun": { calories: 150, protein: 2, carbs: 24, fats: 6, serving: "1 piece" },
    rasgulla: { calories: 100, protein: 2, carbs: 20, fats: 1, serving: "1 piece" },
    rasmalai: { calories: 150, protein: 4, carbs: 20, fats: 6, serving: "1 piece" },
    jalebi: { calories: 150, protein: 1, carbs: 30, fats: 4, serving: "2 pieces" },
    ladoo: { calories: 150, protein: 2, carbs: 24, fats: 6, serving: "1 piece" },
    barfi: { calories: 120, protein: 2, carbs: 18, fats: 5, serving: "1 piece" },
    peda: { calories: 120, protein: 3, carbs: 18, fats: 4, serving: "1 piece" },
    halwa: { calories: 200, protein: 3, carbs: 32, fats: 7, serving: "1/2 cup" },
    "soan papdi": { calories: 100, protein: 1, carbs: 18, fats: 3, serving: "1 piece" },
    "mysore pak": { calories: 150, protein: 2, carbs: 20, fats: 7, serving: "1 piece" },
    "kaju katli": { calories: 120, protein: 2, carbs: 16, fats: 6, serving: "1 piece" },
    chikki: { calories: 120, protein: 2, carbs: 16, fats: 6, serving: "1 piece" },
    "sohan halwa": { calories: 150, protein: 2, carbs: 22, fats: 6, serving: "1 piece" },
    "milk cake": { calories: 150, protein: 4, carbs: 20, fats: 6, serving: "1 piece" },
    "paneer tikka masala": { calories: 300, protein: 14, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer butter masala": { calories: 320, protein: 14, carbs: 14, fats: 22, serving: "1 cup" },
    "shahi paneer": { calories: 320, protein: 14, carbs: 14, fats: 22, serving: "1 cup" },
    "kadai paneer": { calories: 280, protein: 14, carbs: 12, fats: 18, serving: "1 cup" },
    "mutter paneer": { calories: 260, protein: 12, carbs: 16, fats: 16, serving: "1 cup" },
    "paneer bhurji": { calories: 220, protein: 14, carbs: 8, fats: 14, serving: "1 cup" },
    "paneer korma": { calories: 300, protein: 14, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer makhani": { calories: 320, protein: 14, carbs: 14, fats: 22, serving: "1 cup" },
    "paneer malai kofta": { calories: 320, protein: 12, carbs: 16, fats: 22, serving: "1 cup" },
    "paneer tikka roll": { calories: 350, protein: 16, carbs: 30, fats: 16, serving: "1 roll" },
    "paneer sandwich": { calories: 300, protein: 14, carbs: 28, fats: 14, serving: "1 sandwich" },
    "paneer burger": { calories: 350, protein: 14, carbs: 32, fats: 16, serving: "1 burger" },
    "paneer pizza": { calories: 300, protein: 14, carbs: 32, fats: 14, serving: "1 slice" },
    "paneer pasta": { calories: 320, protein: 14, carbs: 36, fats: 14, serving: "1 cup" },
    "paneer noodles": { calories: 300, protein: 12, carbs: 36, fats: 12, serving: "1 cup" },
    "paneer fried rice": { calories: 320, protein: 12, carbs: 42, fats: 12, serving: "1 cup" },
    "paneer manchurian": { calories: 280, protein: 12, carbs: 22, fats: 16, serving: "1 cup" },
    "paneer chilli": { calories: 280, protein: 12, carbs: 22, fats: 16, serving: "1 cup" },
    "paneer 65": { calories: 280, protein: 12, carbs: 18, fats: 16, serving: "1 cup" },
    "paneer pepper fry": { calories: 280, protein: 14, carbs: 10, fats: 18, serving: "1 cup" },
    "paneer ghee roast": { calories: 320, protein: 14, carbs: 10, fats: 22, serving: "1 cup" },
    "paneer kurma": { calories: 280, protein: 12, carbs: 14, fats: 18, serving: "1 cup" },
    "paneer curry": { calories: 280, protein: 14, carbs: 12, fats: 18, serving: "1 cup" },
    "paneer masala": { calories: 280, protein: 14, carbs: 12, fats: 18, serving: "1 cup" },
    "paneer bhaji": { calories: 260, protein: 14, carbs: 12, fats: 16, serving: "1 cup" },
    "paneer sabzi": { calories: 260, protein: 14, carbs: 10, fats: 16, serving: "1 cup" },
    "paneer dal": { calories: 260, protein: 14, carbs: 18, fats: 12, serving: "1 cup" },
    "paneer palak": { calories: 260, protein: 14, carbs: 10, fats: 16, serving: "1 cup" },
    "paneer methi": { calories: 260, protein: 14, carbs: 10, fats: 16, serving: "1 cup" },
    "paneer malai": { calories: 300, protein: 14, carbs: 10, fats: 20, serving: "1 cup" },
    "paneer kofta": { calories: 300, protein: 12, carbs: 16, fats: 20, serving: "1 cup" },
    "paneer pakora": { calories: 200, protein: 8, carbs: 18, fats: 10, serving: "3 pieces" },
    "paneer cutlet": { calories: 180, protein: 8, carbs: 16, fats: 8, serving: "2 pieces" },
    "paneer roll": { calories: 300, protein: 14, carbs: 28, fats: 14, serving: "1 roll" },
    "paneer paratha": { calories: 280, protein: 12, carbs: 28, fats: 14, serving: "1 piece" },
    "paneer kulcha": { calories: 280, protein: 12, carbs: 30, fats: 12, serving: "1 piece" },
    "paneer naan": { calories: 300, protein: 12, carbs: 36, fats: 12, serving: "1 piece" },
    "paneer bhatura": { calories: 350, protein: 12, carbs: 42, fats: 16, serving: "2 pieces" },
    "paneer puri": { calories: 250, protein: 8, carbs: 30, fats: 10, serving: "2 pieces" },
    "paneer idli": { calories: 120, protein: 6, carbs: 18, fats: 3, serving: "2 pieces" },
    "paneer dosa": { calories: 220, protein: 10, carbs: 28, fats: 8, serving: "1 piece" },
    "paneer uttapam": { calories: 180, protein: 8, carbs: 24, fats: 6, serving: "1 piece" },
    "paneer vada": { calories: 180, protein: 8, carbs: 22, fats: 7, serving: "2 pieces" },
    "paneer appe": { calories: 120, protein: 6, carbs: 16, fats: 4, serving: "3 pieces" },
    "paneer pongal": { calories: 200, protein: 8, carbs: 28, fats: 6, serving: "1 cup" },
    "paneer upma": { calories: 180, protein: 8, carbs: 24, fats: 6, serving: "1 cup" },
    "paneer khichdi": { calories: 220, protein: 10, carbs: 28, fats: 8, serving: "1 cup" },
    "paneer pulao": { calories: 260, protein: 10, carbs: 36, fats: 8, serving: "1 cup" },
    "paneer biryani": { calories: 320, protein: 12, carbs: 44, fats: 10, serving: "1 cup" },
    "paneer tehari": { calories: 280, protein: 10, carbs: 40, fats: 8, serving: "1 cup" },
    "paneer kheer": { calories: 220, protein: 8, carbs: 30, fats: 8, serving: "1 cup" },
    "paneer payasam": { calories: 220, protein: 8, carbs: 30, fats: 8, serving: "1 cup" },
    "paneer rabri": { calories: 280, protein: 10, carbs: 28, fats: 12, serving: "1 cup" },
    "paneer basundi": { calories: 280, protein: 10, carbs: 28, fats: 12, serving: "1 cup" },
    "paneer halwa": { calories: 240, protein: 8, carbs: 30, fats: 10, serving: "1/2 cup" },
    "paneer barfi": { calories: 180, protein: 8, carbs: 20, fats: 8, serving: "1 piece" },
    "paneer peda": { calories: 160, protein: 8, carbs: 18, fats: 6, serving: "1 piece" },
    "paneer ladoo": { calories: 180, protein: 8, carbs: 20, fats: 8, serving: "1 piece" },
    "paneer gulab jamun": { calories: 200, protein: 6, carbs: 26, fats: 8, serving: "1 piece" },
    "paneer rasgulla": { calories: 150, protein: 6, carbs: 22, fats: 2, serving: "1 piece" },
    "paneer rasmalai": { calories: 200, protein: 8, carbs: 22, fats: 8, serving: "1 piece" },
    "paneer jalebi": { calories: 200, protein: 6, carbs: 28, fats: 6, serving: "2 pieces" },
    "paneer kulfi": { calories: 180, protein: 6, carbs: 22, fats: 8, serving: "1 piece" },
    "paneer ice cream": { calories: 200, protein: 6, carbs: 24, fats: 10, serving: "1 scoop" },
    "paneer cake": { calories: 250, protein: 8, carbs: 30, fats: 10, serving: "1 slice" },
    "paneer pastry": { calories: 250, protein: 6, carbs: 30, fats: 12, serving: "1 piece" },
    "paneer cookie": { calories: 150, protein: 4, carbs: 18, fats: 6, serving: "2 pieces" },
    "paneer biscuit": { calories: 120, protein: 4, carbs: 16, fats: 4, serving: "3 pieces" },
    "paneer bread": { calories: 150, protein: 6, carbs: 20, fats: 4, serving: "2 slices" },
    "paneer toast": { calories: 180, protein: 8, carbs: 20, fats: 8, serving: "2 slices" },
    "paneer salad": { calories: 150, protein: 10, carbs: 8, fats: 8, serving: "1 bowl" },
    "paneer soup": { calories: 120, protein: 8, carbs: 8, fats: 6, serving: "1 bowl" },
    "paneer smoothie": { calories: 200, protein: 12, carbs: 18, fats: 8, serving: "1 glass" },
    "paneer shake": { calories: 220, protein: 12, carbs: 20, fats: 8, serving: "1 glass" },
    "paneer lassi": { calories: 200, protein: 10, carbs: 18, fats: 8, serving: "1 glass" },
    "paneer chaas": { calories: 120, protein: 8, carbs: 6, fats: 6, serving: "1 glass" },
    "paneer buttermilk": { calories: 120, protein: 8, carbs: 6, fats: 6, serving: "1 glass" },
    "paneer raita": { calories: 120, protein: 8, carbs: 6, fats: 6, serving: "1 cup" },
    "paneer chutney": { calories: 80, protein: 4, carbs: 4, fats: 4, serving: "2 tbsp" },
    "paneer pickle": { calories: 60, protein: 2, carbs: 4, fats: 4, serving: "1 tbsp" },
    "paneer papad": { calories: 80, protein: 4, carbs: 8, fats: 4, serving: "2 pieces" },
    "paneer fryums": { calories: 100, protein: 2, carbs: 12, fats: 4, serving: "handful" },
    "paneer chips": { calories: 150, protein: 4, carbs: 16, fats: 8, serving: "small pack" },
    "paneer popcorn": { calories: 150, protein: 6, carbs: 14, fats: 8, serving: "small bowl" },
    "paneer bites": { calories: 180, protein: 10, carbs: 10, fats: 10, serving: "5 pieces" },
    "paneer nuggets": { calories: 200, protein: 12, carbs: 12, fats: 10, serving: "5 pieces" },
    "paneer fingers": { calories: 180, protein: 10, carbs: 10, fats: 10, serving: "5 pieces" },
    "paneer cubes": { calories: 160, protein: 10, carbs: 6, fats: 10, serving: "5 pieces" },
    "paneer strips": { calories: 180, protein: 10, carbs: 8, fats: 10, serving: "5 pieces" },
    "paneer balls": { calories: 160, protein: 8, carbs: 10, fats: 8, serving: "5 pieces" },
    "paneer rings": { calories: 160, protein: 8, carbs: 12, fats: 8, serving: "5 pieces" },
    "paneer patties": { calories: 180, protein: 8, carbs: 14, fats: 8, serving: "2 pieces" },
    "paneer tikka bites": { calories: 180, protein: 10, carbs: 8, fats: 10, serving: "5 pieces" },
    "paneer malai tikka": { calories: 220, protein: 10, carbs: 8, fats: 14, serving: "4 pieces" },
    "paneer hariyali tikka": { calories: 200, protein: 10, carbs: 6, fats: 12, serving: "4 pieces" },
    "paneer achari tikka": { calories: 200, protein: 10, carbs: 8, fats: 12, serving: "4 pieces" },
    "paneer pudina tikka": { calories: 200, protein: 10, carbs: 6, fats: 12, serving: "4 pieces" },
    "paneer lasooni tikka": { calories: 220, protein: 10, carbs: 6, fats: 14, serving: "4 pieces" },
    "paneer methi tikka": { calories: 200, protein: 10, carbs: 6, fats: 12, serving: "4 pieces" },
    "paneer tandoori": { calories: 220, protein: 12, carbs: 6, fats: 14, serving: "4 pieces" },
    "paneer malai tandoori": { calories: 260, protein: 12, carbs: 6, fats: 18, serving: "4 pieces" },
    "paneer bharta": { calories: 220, protein: 12, carbs: 10, fats: 14, serving: "1 cup" },
    "paneer chaman": { calories: 260, protein: 12, carbs: 10, fats: 18, serving: "1 cup" },
    "paneer dum": { calories: 280, protein: 12, carbs: 12, fats: 18, serving: "1 cup" },
    "paneer kaliya": { calories: 280, protein: 12, carbs: 12, fats: 18, serving: "1 cup" },
    "paneer qorma": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer rezala": { calories: 280, protein: 12, carbs: 12, fats: 18, serving: "1 cup" },
    "paneer salan": { calories: 280, protein: 12, carbs: 12, fats: 18, serving: "1 cup" },
    "paneer masaledar": { calories: 280, protein: 12, carbs: 12, fats: 18, serving: "1 cup" },
    "paneer zaitooni": { calories: 300, protein: 12, carbs: 12, fats: 20, serving: "1 cup" },
    "paneer hara masala": { calories: 260, protein: 12, carbs: 10, fats: 16, serving: "1 cup" },
    "paneer safed masala": { calories: 300, protein: 12, carbs: 12, fats: 20, serving: "1 cup" },
    "paneer methi malai": { calories: 280, protein: 12, carbs: 10, fats: 18, serving: "1 cup" },
    "paneer shahi korma": { calories: 320, protein: 12, carbs: 14, fats: 22, serving: "1 cup" },
    "paneer mughlai": { calories: 320, protein: 12, carbs: 14, fats: 22, serving: "1 cup" },
    "paneer awadhi": { calories: 300, protein: 12, carbs: 12, fats: 20, serving: "1 cup" },
    "paneer lucknowi": { calories: 300, protein: 12, carbs: 12, fats: 20, serving: "1 cup" },
    "paneer hyderabadi": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer chettinad": { calories: 300, protein: 12, carbs: 12, fats: 20, serving: "1 cup" },
    "paneer kolhapuri": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer malvani": { calories: 300, protein: 12, carbs: 12, fats: 20, serving: "1 cup" },
    "paneer goda": { calories: 280, protein: 12, carbs: 12, fats: 18, serving: "1 cup" },
    "paneer varhadi": { calories: 280, protein: 12, carbs: 12, fats: 18, serving: "1 cup" },
    "paneer saoji": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer guntur": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer andhra": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer kerala": { calories: 280, protein: 12, carbs: 12, fats: 18, serving: "1 cup" },
    "paneer mangalorean": { calories: 280, protein: 12, carbs: 12, fats: 18, serving: "1 cup" },
    "paneer udupi": { calories: 260, protein: 12, carbs: 10, fats: 16, serving: "1 cup" },
    "paneer coorg": { calories: 280, protein: 12, carbs: 12, fats: 18, serving: "1 cup" },
    "paneer malnad": { calories: 280, protein: 12, carbs: 12, fats: 18, serving: "1 cup" },
    "paneer bengali": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer odia": { calories: 280, protein: 12, carbs: 12, fats: 18, serving: "1 cup" },
    "paneer assamese": { calories: 280, protein: 12, carbs: 12, fats: 18, serving: "1 cup" },
    "paneer manipuri": { calories: 280, protein: 12, carbs: 12, fats: 18, serving: "1 cup" },
    "paneer nagamese": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer mizo": { calories: 280, protein: 12, carbs: 12, fats: 18, serving: "1 cup" },
    "paneer tripuri": { calories: 280, protein: 12, carbs: 12, fats: 18, serving: "1 cup" },
    "paneer sikkimese": { calories: 280, protein: 12, carbs: 12, fats: 18, serving: "1 cup" },
    "paneer darjeeling": { calories: 280, protein: 12, carbs: 12, fats: 18, serving: "1 cup" },
    "paneer kashmiri": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer himachali": { calories: 280, protein: 12, carbs: 12, fats: 18, serving: "1 cup" },
    "paneer punjabi": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer haryanvi": { calories: 280, protein: 12, carbs: 12, fats: 18, serving: "1 cup" },
    "paneer rajasthani": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer gujarati": { calories: 280, protein: 12, carbs: 12, fats: 18, serving: "1 cup" },
    "paneer marathi": { calories: 280, protein: 12, carbs: 12, fats: 18, serving: "1 cup" },
    "paneer goan": { calories: 280, protein: 12, carbs: 12, fats: 18, serving: "1 cup" },
    "paneer konkani": { calories: 280, protein: 12, carbs: 12, fats: 18, serving: "1 cup" },
    "paneer sindhi": { calories: 280, protein: 12, carbs: 12, fats: 18, serving: "1 cup" },
    "paneer parsi": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer irani": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer english": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer french": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer italian": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer spanish": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer german": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer chinese": { calories: 280, protein: 12, carbs: 12, fats: 18, serving: "1 cup" },
    "paneer japanese": { calories: 280, protein: 12, carbs: 12, fats: 18, serving: "1 cup" },
    "paneer korean": { calories: 280, protein: 12, carbs: 12, fats: 18, serving: "1 cup" },
    "paneer thai": { calories: 280, protein: 12, carbs: 12, fats: 18, serving: "1 cup" },
    "paneer vietnamese": { calories: 280, protein: 12, carbs: 12, fats: 18, serving: "1 cup" },
    "paneer malaysian": { calories: 280, protein: 12, carbs: 12, fats: 18, serving: "1 cup" },
    "paneer indonesian": { calories: 280, protein: 12, carbs: 12, fats: 18, serving: "1 cup" },
    "paneer filipino": { calories: 280, protein: 12, carbs: 12, fats: 18, serving: "1 cup" },
    "paneer singaporean": { calories: 280, protein: 12, carbs: 12, fats: 18, serving: "1 cup" },
    "paneer sri lankan": { calories: 280, protein: 12, carbs: 12, fats: 18, serving: "1 cup" },
    "paneer bangladeshi": { calories: 280, protein: 12, carbs: 12, fats: 18, serving: "1 cup" },
    "paneer nepali": { calories: 280, protein: 12, carbs: 12, fats: 18, serving: "1 cup" },
    "paneer bhutanese": { calories: 280, protein: 12, carbs: 12, fats: 18, serving: "1 cup" },
    "paneer tibetan": { calories: 280, protein: 12, carbs: 12, fats: 18, serving: "1 cup" },
    "paneer afghan": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer persian": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer arabic": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer turkish": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer greek": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer mediterranean": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer mexican": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer brazilian": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer argentinian": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer peruvian": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer colombian": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer venezuelan": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer chilean": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer uruguayan": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer ecuadorian": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer cuban": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer puerto rican": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer dominican": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer jamaican": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer trinidadian": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer haitian": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer barbadian": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer guyanese": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer surinamese": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer belizean": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer costa rican": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer panamanian": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer nicaraguan": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer honduran": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer salvadoran": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer guatemalan": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer zimbabwean": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer zambian": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer malawian": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer mozambican": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer botswanan": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer namibian": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer angolan": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer congolese": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer gabonese": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer cameroonian": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer sudanese": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer south sudanese": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer eritrean": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer djiboutian": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer somali": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer libyan": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer tunisian": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer algerian": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer mauritanian": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer malian": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer burkinabe": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer nigerien": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer senegalese": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer gambian": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer guinean": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer guinean bissau": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer sierra leonean": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer liberian": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer ivorian": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer togolese": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer beninese": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer cape verdean": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer sao tomean": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer equatorial guinean": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer comorian": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer seychellois": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer mauritian": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer reunionese": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer madagascan": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer malagasy": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
    "paneer mayotte": { calories: 300, protein: 12, carbs: 14, fats: 20, serving: "1 cup" },
};

function estimateNutrition(query: string): {
    name: string;
    calories: number;
    protein: number;
    carbs: number;
    fats: number;
    serving: string;
} | null {
    const lowerQuery = query.toLowerCase();

    for (const [key, value] of Object.entries(knownFoods)) {
        if (lowerQuery.includes(key)) {
            return { name: query.trim(), ...value };
        }
    }

    return {
        name: query.trim(),
        calories: 150,
        protein: 5,
        carbs: 20,
        fats: 5,
        serving: "1 serving (estimated)",
    };
}
